#!/bin/sh -e

# we cannot properly synthesize LVM LV change events with udevadm trigger, so
# if we use LVM, we need to let it finish; otherwise we get missing LV symlinks
# (LP #1185394)
if [ -x /sbin/vgchange ]; then
    udevadm settle --timeout=121 || true
fi
