#!/bin/bash

build() {
  add_full_dir /etc/modprobe.d '*.conf'
  add_full_dir /usr/lib/modprobe.d '*.conf'
  add_file '/usr/lib/theinit/fips.conf' '/etc/fips.conf'
  add_file '/usr/lib/theinit/fips.modules' '/etc/fips.modules'
}

help() {
  cat <<HELPEOF
This hook installs modprobe configuration files from /etc/modprobe.d and
/usr/lib/modprobe.d.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
