#!/bin/sh

__TMPEARLYCPIO="$(mktemp "/boot/AMDUCODE_XXXXXX")" || exit 1

AUCODE_FW_DIR=/new_root/lib/firmware/amd-ucode
AMD64UCODE_INITRAMFS=${AMD64UCODE_INITRAMFS:-early}

[ -z "${AMD64UCODE_INITRAMFS}" ] && AMD64UCODE_INITRAMFS=no

if [ ! -d "${AUCODE_FW_DIR}" ] ; then
    exit 0
fi

AMD64UCODE_INITRAMFS=early

EFWD=$(mktemp -d "/boot/mkinitramfs-EFW_XXXXXXXXXX") || {
    exit 1
}

[ ! -d "${EFWD}" ] && {
    exit 1
}

EFWE="${EFWD}/early-initramfs.cpio"
EFWCD="${EFWD}/d/kernel/x86/microcode"
EFWF="${EFWCD}/AuthenticAMD.bin"

mkdir -p "${EFWCD}" && \
 find "${AUCODE_FW_DIR}/." -maxdepth 1 -type f -print0 | LC_ALL=C sort -z | cat 2>/dev/null >"${EFWF}" && \
 find "${EFWD}" -print0 | ( cd "${EFWD}/d" ; find . -print0 | LC_ALL=C sort -z | cpio -0 -H newc -o )

[ -d "${EFWD}" ] && rm -fr "${EFWD}"
